/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  ActivateDeviceArgs,
  activateDeviceArgsBeet,
} from '../types/ActivateDeviceArgs.js'

import { PROGRAM_ID } from '../../constants.js'

/**
 * @category Instructions
 * @category ActivateDevice
 * @category generated
 */
export type ActivateDeviceInstructionArgs = {
  args: ActivateDeviceArgs
}
/**
 * @category Instructions
 * @category ActivateDevice
 * @category generated
 */
export const activateDeviceStruct = new beet.FixableBeetArgsStruct<
  ActivateDeviceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', activateDeviceArgsBeet],
  ],
  'ActivateDeviceInstructionArgs',
)
/**
 * Accounts required by the _activateDevice_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] device
 * @category Instructions
 * @category ActivateDevice
 * @category generated
 */
export type ActivateDeviceInstructionAccounts = {
  payer: web3.PublicKey
  device: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const activateDeviceInstructionDiscriminator = [
  252, 7, 51, 64, 77, 224, 215, 201,
]

/**
 * Creates a _ActivateDevice_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ActivateDevice
 * @category generated
 */

export function createActivateDeviceInstruction(
  accounts: ActivateDeviceInstructionAccounts,
  args: ActivateDeviceInstructionArgs,
  programId = new web3.PublicKey(
    PROGRAM_ID,
  ),
) {
  const [data] = activateDeviceStruct.serialize({
    instructionDiscriminator: activateDeviceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.device,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
