/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateVendorArgs,
  createVendorArgsBeet,
} from '../types/CreateVendorArgs.js'

import { PROGRAM_ID } from '../../constants.js'

/**
 * @category Instructions
 * @category CreateVendor
 * @category generated
 */
export type CreateVendorInstructionArgs = {
  args: CreateVendorArgs
}
/**
 * @category Instructions
 * @category CreateVendor
 * @category generated
 */
export const createVendorStruct = new beet.FixableBeetArgsStruct<
  CreateVendorInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createVendorArgsBeet],
  ],
  'CreateVendorInstructionArgs',
)
/**
 * Accounts required by the _createVendor_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] global
 * @property [**signer**] adminKey
 * @property [_writable_] vendor
 * @category Instructions
 * @category CreateVendor
 * @category generated
 */
export type CreateVendorInstructionAccounts = {
  payer: web3.PublicKey
  global: web3.PublicKey
  adminKey: web3.PublicKey
  vendor: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createVendorInstructionDiscriminator = [
  32, 63, 115, 119, 35, 61, 109, 155,
]

/**
 * Creates a _CreateVendor_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateVendor
 * @category generated
 */

export function createCreateVendorInstruction(
  accounts: CreateVendorInstructionAccounts,
  args: CreateVendorInstructionArgs,
  programId = new web3.PublicKey(
    PROGRAM_ID,
  ),
) {
  const [data] = createVendorStruct.serialize({
    instructionDiscriminator: createVendorInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.global,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminKey,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.vendor,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
