/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  InitializeGlobalArgs,
  initializeGlobalArgsBeet,
} from '../types/InitializeGlobalArgs.js'

/**
 * @category Instructions
 * @category InitializeGlobal
 * @category generated
 */
export type InitializeGlobalInstructionArgs = {
  args: InitializeGlobalArgs
}
/**
 * @category Instructions
 * @category InitializeGlobal
 * @category generated
 */
export const initializeGlobalStruct = new beet.BeetArgsStruct<
  InitializeGlobalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', initializeGlobalArgsBeet],
  ],
  'InitializeGlobalInstructionArgs',
)
/**
 * Accounts required by the _initializeGlobal_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [] admin
 * @property [**signer**] adminKey
 * @property [_writable_] global
 * @category Instructions
 * @category InitializeGlobal
 * @category generated
 */
export type InitializeGlobalInstructionAccounts = {
  payer: web3.PublicKey
  admin: web3.PublicKey
  adminKey: web3.PublicKey
  global: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeGlobalInstructionDiscriminator = [
  47, 225, 15, 112, 86, 51, 190, 231,
]

/**
 * Creates a _InitializeGlobal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeGlobal
 * @category generated
 */
export function createInitializeGlobalInstruction(
  accounts: InitializeGlobalInstructionAccounts,
  args: InitializeGlobalInstructionArgs,
  programId = new web3.PublicKey(
    '1234WPYMnkT2bx5MB3uLmixeDuaCHDpd3mXNhZGimKWg',
  ),
) {
  const [data] = initializeGlobalStruct.serialize({
    instructionDiscriminator: initializeGlobalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.adminKey,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.global,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
