/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  InitializeAdminArgs,
  initializeAdminArgsBeet,
} from '../types/InitializeAdminArgs.js'

import { PROGRAM_ID } from '../../constants.js'

/**
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export type InitializeAdminInstructionArgs = {
  args: InitializeAdminArgs
}
/**
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export const initializeAdminStruct = new beet.BeetArgsStruct<
  InitializeAdminInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', initializeAdminArgsBeet],
  ],
  'InitializeAdminInstructionArgs',
)
/**
 * Accounts required by the _initializeAdmin_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] admin
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export type InitializeAdminInstructionAccounts = {
  payer: web3.PublicKey
  admin: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeAdminInstructionDiscriminator = [
  35, 176, 8, 143, 42, 160, 61, 158,
]

/**
 * Creates a _InitializeAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */

export function createInitializeAdminInstruction(
  accounts: InitializeAdminInstructionAccounts,
  args: InitializeAdminInstructionArgs,
  programId = new web3.PublicKey(
    PROGRAM_ID ,
  ),
) {
  const [data] = initializeAdminStruct.serialize({
    instructionDiscriminator: initializeAdminInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
