/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Product}
 * @category Accounts
 * @category generated
 */
export type ProductArgs = {
  name: string
  devicesNums: number
  bumpSeed: number
}

export const productDiscriminator = [102, 76, 55, 251, 38, 73, 224, 229]
/**
 * Holds the data for the {@link Product} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Product implements ProductArgs {
  private constructor(
    readonly name: string,
    readonly devicesNums: number,
    readonly bumpSeed: number,
  ) {}

  /**
   * Creates a {@link Product} instance from the provided args.
   */
  static fromArgs(args: ProductArgs) {
    return new Product(args.name, args.devicesNums, args.bumpSeed)
  }

  /**
   * Deserializes the {@link Product} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Product, number] {
    return Product.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Product} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Product> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Product account at ${address}`)
    }
    return Product.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '1234WPYMnkT2bx5MB3uLmixeDuaCHDpd3mXNhZGimKWg',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, productBeet)
  }

  /**
   * Deserializes the {@link Product} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Product, number] {
    return productBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Product} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return productBeet.serialize({
      accountDiscriminator: productDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Product} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: ProductArgs) {
    const instance = Product.fromArgs(args)
    return productBeet.toFixedFromValue({
      accountDiscriminator: productDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Product} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: ProductArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Product.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link Product} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      name: this.name,
      devicesNums: this.devicesNums,
      bumpSeed: this.bumpSeed,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const productBeet = new beet.FixableBeetStruct<
  Product,
  ProductArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['name', beet.utf8String],
    ['devicesNums', beet.u32],
    ['bumpSeed', beet.u8],
  ],
  Product.fromArgs,
  'Product',
)
